name: Terraform & Ansible Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout Repo
      - name: Checkout Repo
        uses: actions/checkout@v4

      # 2. Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      # 3. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 4. Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 5. Terraform Plan
      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -var "public_key=${{ secrets.PUBLIC_KEY }}"

      # 6. Terraform Apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var "public_key=${{ secrets.PUBLIC_KEY }}"

      # 7. Get EC2 Public IP
      - name: Get EC2 Public IP
        id: tf_output
        working-directory: terraform
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          echo "EC2 Public IP: $PUBLIC_IP"

      # 8. Install Ansible
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      # 9. Save Private Key for Ansible
      - name: Save private key
        run: |
          echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ansible_id_rsa
          chmod 600 ansible_id_rsa

      # 10. Run Ansible Playbook
      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          echo "Using PUBLIC_IP=${PUBLIC_IP}"
          echo "[web]" > inventory.ini
          echo "${PUBLIC_IP} ansible_user=ubuntu ansible_ssh_private_key_file=${{ github.workspace }}/ansible_id_rsa" >> inventory.ini
          cat inventory.ini
          ansible-playbook -i inventory.ini playbook.yml --ssh-extra-args="-o StrictHostKeyChecking=no"
