name: Terraform & Ansible Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Generate SSH Key Pair
        run: |
          ssh-keygen -t rsa -b 4096 -f deploy_key -q -N ""
          echo "PUBLIC_KEY=$(cat deploy_key.pub)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan -var "public_key=${{ secrets.PUBLIC_KEY }}"

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var "public_key=${PUBLIC_KEY}"

      - name: Export Public IP
        id: ip
        working-directory: terraform
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV
          echo "EC2 Public IP: $PUBLIC_IP"

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Save private key
        run: |
          cp deploy_key ansible_id_rsa
          chmod 600 ansible_id_rsa

      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          echo "Using PUBLIC_IP=${PUBLIC_IP}"
          echo "[web]" > inventory.ini
          echo "${PUBLIC_IP} ansible_user=ubuntu ansible_ssh_private_key_file=$(pwd)/../ansible_id_rsa" >> inventory.ini
          echo "Generated Inventory:"
          cat inventory.ini
          ansible-playbook -i inventory.ini playbook.yml --ssh-extra-args="-o StrictHostKeyChecking=no"
